### ISSUE TITLE
npm run dev fails with error

### ISSUE THREAD

**Issue by sr6033** [joway/burrow-dashboard#49]
**Error log:**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle burrow-dashboard@1.0.4~predev: burrow-dashboard@1.0.4
6 info lifecycle burrow-dashboard@1.0.4~dev: burrow-dashboard@1.0.4
7 verbose lifecycle burrow-dashboard@1.0.4~dev: unsafe-perm in lifecycle true
8 verbose lifecycle burrow-dashboard@1.0.4~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/param/burrow-dashboard/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sb$
9 verbose lifecycle burrow-dashboard@1.0.4~dev: CWD: /home/param/burrow-dashboard
10 silly lifecycle burrow-dashboard@1.0.4~dev: Args: [ '-c',
10 silly lifecycle   'webpack-dev-server --inline --progress --config build/webpack.dev.conf.js' ]
11 silly lifecycle burrow-dashboard@1.0.4~dev: Returned: code: 1  signal: null
12 info lifecycle burrow-dashboard@1.0.4~dev: Failed to exec dev script
13 verbose stack Error: burrow-dashboard@1.0.4 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid burrow-dashboard@1.0.4
15 verbose cwd /home/param/burrow-dashboard
16 verbose Linux 4.15.0-1027-gcp
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error burrow-dashboard@1.0.4 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
22 error Exit status 1
23 error Failed at the burrow-dashboard@1.0.4 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by joway** [comment]
@sr6033  Hi, I have fixed the error ,plz try again.

Thanks for your report!
