### ISSUE TITLE
Docker build fails node 12

### ISSUE THREAD

**Issue by cdenneen** [joway/burrow-dashboard#53]
@joway have you built this recently maybe need to use older version of node?
Here is the beginning of the pages of errors trying to do the install:

```
burrow/burrow-dashboard - [master] » npm install

> fsevents@1.2.7 install /Users/cdenneen/work/burrow/burrow-dashboard/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and node@12.4.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@12.4.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
In file included from In file included from ../../nan/nan.h../../nan/nan.h::222222:
:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:202:1: note: expanded from here
ToBoolean
^
: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:202:1: note: expanded from here
ToBoolean
^
/Users/cdenneen/.node-gyp/12.4.0/include/node/v8.h:/Users/cdenneen/.node-gyp/12.4.0/include/node/v8.h2523:2523::33::  note: note'ToBoolean':  has 'ToBoolean'been  explicitlyhas  markedbeen deprecated  explicitlyhere marked
 deprecated here
  V8_DEPRECATE_SOON("ToBoolean can never throw. Use Local version.",
  ^
  V8_DEPRECATE_SOON("ToBoolean can never throw. Use Local version.",
  ^
```

**Comment by cdenneen** [comment]
I checked out 1.0.3 and it seems to get further but error here:

```
31854 verbose stack Error: vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
31854 verbose stack spawn ENOENT
31854 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
31854 verbose stack     at ChildProcess.emit (events.js:200:13)
31854 verbose stack     at maybeClose (internal/child_process.js:1021:16)
31854 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
31855 verbose pkgid vue-material@1.0.0
31856 verbose cwd /Users/cdenneen/work/burrow/burrow-dashboard
31857 verbose Darwin 18.5.0
31858 verbose argv "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/bin/npm" "install"
31859 verbose node v12.4.0
31860 verbose npm  v6.9.0
31861 error file sh
31862 error code ELIFECYCLE
31863 error errno ENOENT
31864 error syscall spawn
31865 error vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
31865 error spawn ENOENT
31866 error Failed at the vue-material@1.0.0 postinstall script.
31866 error This is probably not a problem with npm. There is likely additional logging output above.
31867 verbose exit [ 1, true ]
```

**Comment by joway** [comment]
@cdenneen  Hi, I cannot reproduce your error in my Macbook. But I have create a new dockerfile https://github.com/joway/burrow-dashboard/commit/3c3f5b685da57947673918741edc58703fe19387.

You can try to build code in docker.
